[package]
name = "first_ray_tracer"
version = "0.1.0"
authors = ["Christoph Bonitz <christoph.bonitz@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.18.0"
image = "0.21.2"
rand = "0.7.0"
rayon = "1.1.0"