[package]
name = "first_ray_tracer"
version = "0.1.0"
authors = ["Christoph Bonitz <christoph.bonitz@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.16.13"
image = "0.21.0"
rand = "0.6.4"
rayon = "1.0"